#!/usr/bin/python3
# SPDX-FileCopyrightText: 2024 Daichi Aida <da1649ichi@gmail.com>
# SPDX-License-Identifier: BSD-3-Clause

import sys

input_lines = sys.stdin.read().strip().split("\n")

for line in input_lines:
    if not all(char.islower() for char in line):
        sys.exit(1)

processed_lines = [line.upper() for line in input_lines]

for line in processed_lines: 
    print(line)
