#!/usr/bin/python3
# SPDX-FileCopyrightText: 2024 Daichi Aida <da1649ichi@gmail.com>
# SPDX-License-Identifier: BSD-3-Clause
import sys
   
ans = 0
for line in sys.stdin:
    ans += int(line)

print(ans)
